# SPDX-License-Identifier: BSD-3-Clause-Clear


obj-$(CONFIG_NRC7394) += nrc_core.o

nrc_core-y := hif.o \
	      wim.o \
	      nrc-init.o \
	      nrc-dump.o \
	      nrc-bd.o \
	      nrc-debug.o \
	      nrc-hal-callback.o \
	      nrc-hal-ops-impl.o \
	      nrc-hal-export.o \
	      nrc-fw.o \
	      nrc-hal-init.o \
	      nrc-tx.o \
	      nrc-ps.o \
	      nrc-recovery.o
