# SPDX-License-Identifier: GPL-2.0
#
# Kbuild file for NRC7394 Modular Driver
# This file is used when building as part of the kernel tree or with M= option
#

# Recurse into subdirectories for module building
obj-$(CONFIG_NRC7394) += backend/nrc_spi/
obj-$(CONFIG_NRC7394) += hal/nrc_core/
obj-$(CONFIG_NRC7394) += frontend/nrc_wlan/
obj-$(CONFIG_NRC7394_MCP) += frontend/nrc_mcp/
